#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: tagsList_screen
  screens: 
    tagsList_screen: &tagsList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Tags
      title: _("List of %s %2s", ngettext('Tag', 'Tags', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            tagsEdit_screen: true
          dialogs: 
            tagsDel_dialog: true
          default: tagsEdit_screen
      options: 
        title: _("Options")
        screens: 
          tagsNew_screen: true
        dialogs: 
          tagsDel_dialog: true
    tagsNew_screen: &tagsNew_screenLink 
      <<: *Tags
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Tag', 'Tags', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          lastModified: true
    tagsEdit_screen: &tagsEdit_screenLink 
      <<: *Tags
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Tag', 'Tags', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          lastModified: true
  dialogs: 
    tagsDel_dialog: 
      <<: *Tags
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Tag', 'Tags', 1))
      description: _("Do you want to delete this %s?", ngettext('Tag', 'Tags', 1))
      message: _("%s successfully deleted.", ngettext('Tag', 'Tags', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
