production: 
  class: \Librecon\Model\KlearRoles
  fields: 
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      default: true
    description: 
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      defaultValue: 
    identifier: 
      title: ngettext('Identifier', 'Identifiers', 1)
      type: text
      required: true
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
